### ISSUE TITLE
Special Character in Master Item Name

### ISSUE THREAD

**Issue by Rock-VbCity** [djaskowiak/grouped-container#1]
I used to write object names with an underscore (_) to separate words, when I have two button with these names:
**tgtBtnYTD** and **tgtBtnYTD_PY**, the configuration pane shows two: **tgtBtnYTD**; the underscore character is valid as a variable name, so it should not generate this problem.

**Comment by djaskowiak** [comment]
Thank you for bringing this to my attention. I have changed this behavior. Now I use '~' as the sign to concatenate information within the model.  Please use version 1.0.1.

You also need to pick your Master Items again in already build grouped-containers to apply the new values.

Here you can find the new release: [version1.0.1](https://github.com/djaskowiak/grouped-container/releases/tag/1.0)
