### ISSUE TITLE
It is  properly not working in Qlik sense Desk top version

### ISSUE THREAD

**Issue by AlexNomd** [djaskowiak/grouped-container#10]
It is not properly working on qlik sense desktop version, I cannot  select master items, error showing when adding master items "No Master Objects". How can I solve this issue..?
![Grouped Container Error](https://user-images.githubusercontent.com/119648968/206093267-967258b6-1b2b-4059-8f4c-36e78beeea9e.jpg)

**Comment by djaskowiak** [comment]
Hi @AlexNomd I tried it localy with Qlik Sense Desktop Version November 2022 Patch 3 and it worked like a charm. The extension directly started to look up and display my  Masteritems. After that it was possible to work with it. Did you try to use the most current version von the extension and QS Desktop?
