### ISSUE TITLE
Getting error invalid parameters when object is added as Mater item

### ISSUE THREAD

**Issue by kdober** [djaskowiak/grouped-container#9]
Hi!

First of all, great extension.
On version 1.03 the extension causes a pop up with the error 'Invalid parameters' after adding the object as a master item.
![image](https://user-images.githubusercontent.com/11008090/204549323-160cbdd6-11ab-4485-81ed-da829e534681.png)

Steps to replicate:
1 ) On an empty sheet add a Grouped container object.
2) Add a filter or any object into it (works fine to this point)
3) Add the grouped container as a master item with a name and tags. You get the error (probably just after hitting 'ok', if not, after re-entering the sheet)

Additionally, when NOT defined as master item, on the console there is a warning that wasn't on the previous versions.
![image](https://user-images.githubusercontent.com/11008090/204550316-f4854bbc-c410-4be5-a636-afb383dc69da.png)

Cheers
Cristian

**Comment by djaskowiak** [comment]
It was possible to reproduce the issue. As soon the object becomes a master obeject it's property structure changes and a qExtendsId gets set. This id references to the master and "/qHyperCubeDef/qDimensions" & "/qHyperCubeDef/qMeasures" are not longer available to apply patches. 

This issue will be fixed with version 1.0.4. It is planed to be delivered within the next few days.

**Comment by kdober** [comment]
Hi Dennis. Excellent, thanks!!
Could you point me out where i can read about how the extension data structure changes between an standard object and when it becomes a master item?

Thanks 😀

**Comment by djaskowiak** [comment]
It's a property in `qHyperCubeDef`. When it is a normal object it has the properties `qDimensions` and `qMeasures` to save dimensions and measures. Once we turn it into a master object this properties disappear and `qHyperCubeDef` has the property `qExtendsId` to reference a master object. In the code we apply patches to `qHyperCubeDef` for `qDimensions` and `qMeasures`. The patch can't find the corresponding property and starts to throw an error. 

I patched this issue in the controller.js line 34.
Before we try to apply patches to the engine the code asks if the object has a reference to a master object. If this is true it won't apply the patch. 

Hope this helps and explains the behaviour. Thank you very much for bringing this to my attention.

**Comment by kdober** [comment]
Thanks!!. I have started playing with extension few months ago and this is useful info for me :)
